//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEarning
    {
        public int ID { get; set; }
        public Nullable<int> InstrumentID { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> Annual { get; set; }
        public Nullable<decimal> Q1 { get; set; }
        public Nullable<decimal> Q2 { get; set; }
        public Nullable<decimal> Q3 { get; set; }
        public Nullable<decimal> Q4 { get; set; }
        public Nullable<int> Currency { get; set; }
        public string Status { get; set; }
        public string InstrumentCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
