//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateAction
    {
        public int ID { get; set; }
        public string InstrumentCode { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> ExDate { get; set; }
        public string ActionCode { get; set; }
        public Nullable<decimal> SplitRatio { get; set; }
        public Nullable<decimal> Issue { get; set; }
        public Nullable<decimal> Share { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual CorporateActionType CorporateActionType { get; set; }
        public virtual Instrument Instrument { get; set; }
    }
}
