//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public string CountryCode { get; set; }
        public string Capital { get; set; }
        public string City { get; set; }
        public string AdjcentCity { get; set; }
        public string CurrencyDescription { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrShortName { get; set; }
    }
}
