//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        public long Id { get; set; }
        public string InstrumentCode { get; set; }
        public Nullable<decimal> CashDividend { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> XDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Status { get; set; }
        public string ShareType { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
