//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.CompanyEarnings = new HashSet<CompanyEarning>();
            this.CorporateActions = new HashSet<CorporateAction>();
            this.Dividends = new HashSet<Dividend>();
            this.FinancialDueDates = new HashSet<FinancialDueDate>();
            this.Currencies = new HashSet<Currency>();
        }
    
        public int IdInstrument { get; set; }
        public string ISIN { get; set; }
        public Nullable<int> IdInstrumentType { get; set; }
        public Nullable<int> IdSector { get; set; }
        public Nullable<int> IdMarketSegment { get; set; }
        public Nullable<int> InstrumentTypeId { get; set; }
        public Nullable<decimal> DaysClose { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string WebAddress { get; set; }
        public string InstrumentCode { get; set; }
        public string InstrumentName { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public string Suspended { get; set; }
        public string Tradeable { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string InstrumentShortName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEarning> CompanyEarnings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateAction> CorporateActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dividend> Dividends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialDueDate> FinancialDueDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency> Currencies { get; set; }
    }
}
