//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS2.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebFeedRepositoryEntities : DbContext
    {
        public WebFeedRepositoryEntities()
            : base("name=WebFeedRepositoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BondIndex> BondIndexes { get; set; }
        public virtual DbSet<BondIndexDetail> BondIndexDetails { get; set; }
        public virtual DbSet<CompanyEarning> CompanyEarnings { get; set; }
        public virtual DbSet<CorporateAction> CorporateActions { get; set; }
        public virtual DbSet<CorporateActionType> CorporateActionTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dividend> Dividends { get; set; }
        public virtual DbSet<FinancialDueDate> FinancialDueDates { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<StockType> StockTypes { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
    
        public virtual ObjectResult<usp_GetBondIndex_Result> usp_GetBondIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBondIndex_Result>("usp_GetBondIndex");
        }
    
        public virtual ObjectResult<usp_GetCompanyEarnings_Result> usp_GetCompanyEarnings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCompanyEarnings_Result>("usp_GetCompanyEarnings");
        }
    
        public virtual ObjectResult<usp_GetCorporateActions_Result> usp_GetCorporateActions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCorporateActions_Result>("usp_GetCorporateActions");
        }
    
        public virtual ObjectResult<usp_GetCorporateActionsTypes_Result> usp_GetCorporateActionsTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCorporateActionsTypes_Result>("usp_GetCorporateActionsTypes");
        }
    
        public virtual ObjectResult<usp_GetCountries_Result> usp_GetCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCountries_Result>("usp_GetCountries");
        }
    
        public virtual ObjectResult<usp_GetCurrencies_Result> usp_GetCurrencies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCurrencies_Result>("usp_GetCurrencies");
        }
    
        public virtual ObjectResult<usp_GetDividend_Result> usp_GetDividend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDividend_Result>("usp_GetDividend");
        }
    
        public virtual ObjectResult<usp_GetStockTypes_Result> usp_GetStockTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetStockTypes_Result>("usp_GetStockTypes");
        }
    
        public virtual ObjectResult<usp_GetSymbols_Result> usp_GetSymbols()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSymbols_Result>("usp_GetSymbols");
        }
    
        public virtual ObjectResult<usp_CorporateActionListing_Result> usp_CorporateActionListing(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CorporateActionListing_Result>("usp_CorporateActionListing", startDateParameter, endDateParameter);
        }
    }
}
